[FEATURE] add  intermediate result output
seqan/iGenVar pull request #133
Opened 2021-05-31 09:17 UTC by eldariont

For investigating specific variants, improving our heuristics and parameters and debugging it would be very helpful to view the junctions and clusters generated by iGenVar. However, we currently only output the final variants in VCF.

This PR adds two CLI parameters that the user can set to define file paths where junctions and clusters are output to.

2021-06-01 09:00 UTC, SGSSGene requested changes
Just a few minor things :+1:

2021-06-07 08:54 UTC, eldariont commented on test/cli/iGenVar_cli_test.cpp
> +    "          granted.\n"
This sentence is added by the `seqan3::output_file_validator`.

In `iGenVar.cpp`:
```
parser.add_option(args.junctions_file_path, 'u', "junctions",
                      "The path of the optional junction output file. If no path is given, junctions will not be output.",
                      seqan3::option_spec::advanced,
                      seqan3::output_file_validator{seqan3::output_file_open_options::open_or_create});
```

In https://github.com/seqan/seqan3/blob/f5e732d5e6e6da771a071acb695a9a2b39c29432/include/seqan3/argument_parser/validators.hpp#L729:
```
if (mode == output_file_open_options::open_or_create)
    return "Write permissions must be granted." + valid_extensions_help_page_message();
```

2021-06-07 12:47 UTC, SGSSGene approved these changes
Good work!

2021-06-08 09:05 UTC, Irallia approved these changes
Thanks for your work! 

From the CI I found `Option Identifier 'u' was already used before.`

After solving this, lets see if the coverage still makes Problems.

2021-06-08 09:05 UTC, Irallia commented on test/cli/iGenVar_cli_test.cpp
> +    //this does not specifically check if file exists, rather if its readable.
```suggestion
    // This does not specifically check if file exists, rather if its readable.
```

2021-06-08 09:05 UTC, Irallia commented on test/cli/iGenVar_cli_test.cpp
> +    //this does not specifically check if file exists, rather if its readable.
```suggestion
    // This does not specifically check if file exists, rather if its readable.
```

2021-06-08 11:07 UTC, merged