[FEATURE] set number of decompression threads
seqan/iGenVar pull request #134
Opened 2021-05-31 10:02 UTC by eldariont

This PR fixes #129.

Changes:
- add CLI parameter --threads (default 1)
- use its value to set number of decompression threads
- rename -t (max_tol_inserted_length) to -q to associate --threads with -t

2021-06-01 13:41 UTC, MitraDarja approved these changes
LGTM, just one minor thing. :)

2021-06-01 13:41 UTC, MitraDarja commented on src/iGenVar.cpp
Alphabtical order?
```suggestion
#include <seqan3/contrib/stream/bgzf_stream_util.hpp> // for bgzf_thread_count
#include <seqan3/core/debug_stream.hpp> // for seqan3::debug_stream
```

2021-06-01 15:37 UTC, Irallia requested changes
LGFM, just the one open comment from Mitra.

2021-06-07 10:14 UTC, Irallia approved these changes
Perfect! Thank you!

2021-06-07 10:15 UTC, merged