[FEATURE] Add quality and cutoff parameters
seqan/iGenVar pull request #135
Opened 2021-06-01 11:00 UTC by Irallia

For our very first benchmarks we realized, that these two parameters make a huge difference on our results:
- the filtering cutoff for the sv results (default 1 read)
- the cutoff for the hierarchical clustering (default distance of 10)

Thus I made two commits to add these values to our input parameters:
- [FEATURE] Add a quality input parameter for SVs (amount of supporting reads).
- [FEATURE] Add a clustering cutoff parameter for the hierarchical clustering

2021-06-01 13:49 UTC, MitraDarja approved these changes

2021-06-07 09:20 UTC, eldariont requested changes
Looks great 👍 Just two small comments.

2021-06-07 09:20 UTC, eldariont commented on include/iGenVar.hpp
> +    int32_t sv_qual = 1;
I would rename to `min_qual` to make clear that this is a cutoff.

2021-06-07 09:20 UTC, eldariont commented on src/iGenVar.cpp
> +                      "Specify the minimum quality (amout of supporting reads) of a strucutral variant. "
```suggestion
                      "Specify the minimum quality (amount of supporting reads) of a structural variant to be reported in the vcf output file."
```

The first two changes are typos that should be corrected also in `variant_output.hpp` and `iGenVar.hpp`. The last one is just a suggestion.

2021-06-08 07:56 UTC, eldariont approved these changes
🎉

2021-06-08 07:57 UTC, merged