update bamit library to include read depth sampling functionality.
seqan/iGenVar pull request #181
Opened 2021-11-18 08:20 UTC by joshuak94

2021-11-18 08:32 UTC, joshuak94 commented
No idea why code coverage is decreasing in variant_output.cpp.....

2021-11-18 11:20 UTC, joshuak94 commented
Okay I added a small test in the API to make the code coverage slightly better...

2021-11-18 14:18 UTC, Irallia requested changes

2021-11-18 14:18 UTC, Irallia commented on test/api/input_file_test.cpp
> +#include "variant_detection/variant_output.hpp"  // for output_file_fail()
```suggestion
#include "variant_detection/variant_detection.hpp"  // for detect_junctions_in_long_reads_sam_file()
#include "variant_detection/variant_output.hpp"       // for find_and_output_variants()
```

2021-11-22 14:22 UTC, Irallia approved these changes

2021-11-22 14:22 UTC, merged