[TEST] Add CLI tests for find_deletions.
seqan/iGenVar pull request #22
Opened 2020-10-05 10:33 UTC by simonsasse

Inspired by the other CLI tests. Probably won't build, because no `make` is called before `ctest` or `make test`.

2020-10-06 08:42 UTC, Irallia approved these changes
Perfect thank you!

2020-10-12 13:48 UTC, joergi-w requested changes

2020-10-19 08:01 UTC, simonsasse commented on test/cli/find_deletions_cli_test.cpp
> +        "chr21	11104574	.	N	<DEL>	60	PASS	SVTYPE=DEL;SVLEN=-248;END=11104822\n"
Good point, done ! 👍

2020-10-19 12:16 UTC, joergi-w approved these changes
Good, thanks!

2020-10-19 13:15 UTC, merged