[INFRA] Update cmake version from 3.11.4 to 3.16.0
seqan/iGenVar pull request #235
Opened 2022-09-29 14:06 UTC by Irallia

2022-09-29 18:08 UTC, smehringer approved these changes

2022-09-30 16:59 UTC, eseiler requested changes

2022-09-30 16:59 UTC, eseiler commented on .github/workflows/ci_linux.yml
> +  CMAKE_VERSION: 3.16.0
This should be 3.16.9 (latest patch level). Googletest will require at least 3.16.3 when updated

2022-09-30 16:59 UTC, eseiler commented on CMakeLists.txt
Strictly speaking, you don't need to modify the version here. You don't use any features that require a higher version. SeqAn will already check for 3.16

2022-10-04 12:07 UTC, merged

2022-10-04 12:11 UTC, Irallia commented
I have accidentally merged, I will do the change to 3.16.9 in https://github.com/seqan/iGenVar/pull/218