Add overload function for output to std::cout. Remove mandatory requi…
seqan/iGenVar pull request #39
Opened 2021-01-18 15:19 UTC by joshuak94

…rement for output file option. Add testing.

Addresses #38. Output file is no longer a mandatory option. If called without an output file given, will output to std::cout by default.

Note: I didn't do this very efficiently... Created an overload function which resulted in a bit of code duplication, but I couldn't think of a clever way to allow passing a filesystem path OR std::cout without opening the ostream in main.cpp.

2021-01-21 11:01 UTC, joergi-w requested changes
I make a suggestion to avoid the code duplication.

2021-01-22 11:58 UTC, joshuak94 commented on src/find_deletions/deletion_finding_and_printing.cpp
> +void find_and_print_deletions(std::filesystem::path const & junction_file_path)
!! Thanks for this! I knew there was a better way, I just couldn't think of a simple way to do it...

2021-01-22 13:29 UTC, joergi-w approved these changes
Looks great! 
I found one typo:

2021-01-22 13:29 UTC, joergi-w commented on src/find_deletions/deletion_finding_and_printing.cpp
> + * \param out_stream ouput stream object
```suggestion
 * \param out_stream output stream object
```

2021-01-25 11:33 UTC, Irallia approved these changes
Thank you! 
Could you add to your PR description: `Resolves #38` ?
And I found some style things, nothing important, but maybe yo have some time for new lines. ❤️

2021-01-25 11:33 UTC, Irallia commented on include/find_deletions/deletion_finding_and_printing.hpp
>  void find_and_print_deletions(std::filesystem::path const & junction_file_path, std::filesystem::path const & output_file_path);
Can you insert a line break? We want to have a limit of 120 characters per line.

2021-01-25 11:33 UTC, Irallia commented on src/find_deletions.cpp
> +    parser.add_option(args.output_file_path, 'o', "output", "The path of the vcf output file. If no path is given, will output to standard output.");
line breack please 💅

2021-01-25 11:33 UTC, Irallia commented on src/find_deletions/deletion_finding_and_printing.cpp
>  void find_and_print_deletions(std::filesystem::path const & junction_file_path, std::filesystem::path const & output_file_path)
line breack plz 💅 I know some of them were already there. 😅

2021-01-25 16:54 UTC, Irallia approved these changes
Thank you!

2021-01-26 10:36 UTC, merged