[FIX] Rearrange parameters of analyze_cigar()
seqan/iGenVar pull request #53
Opened 2021-02-09 11:44 UTC by Irallia

Resolves #52 

I made a mix up in the analyze_cigar(), which caused a wrong output.
=> I Rearranged the parameters of analyze_cigar()
I also made const parameter const, repaired the tests and updated the documentation

2021-02-09 14:20 UTC, eldariont approved these changes
Thanks @Irallia for finding and fixing the problem! :+1:

2021-02-14 16:40 UTC, SGSSGene requested changes
Besides a minor typo (that was not introduced by your changes).  It looks good to me.

2021-02-14 16:40 UTC, SGSSGene commented on test/api/junction_detection_test.cpp
>  // Explanation for the stings:
stings → strings

2021-02-14 16:40 UTC, SGSSGene commented on src/detect_breakends/junction_detection.cpp
> +        const auto header_ptr                   = seqan3::get<seqan3::field::header_ptr>(rec);
uh! very nice to read assignment table! :+1:

2021-02-23 13:42 UTC, SGSSGene approved these changes
:+1:

2021-02-23 15:26 UTC, merged