[TEST] Add help page cli tests
seqan/iGenVar pull request #72
Opened 2021-02-18 14:28 UTC by Irallia

Resolves #71

2021-02-18 15:44 UTC, Irallia commented on test/cli/detect_breakends_cli_test.cpp
> +        "          [2,sViper_refinement_method,sViper_refinement_method,2,no_refinement,no_refinement].\n"
Why are these so wrong?
```suggestion
        "    -c, --clustering_method (clustering_methods)\n"
        "          Choose the clustering method to be used. Default: simple_clustering.\n"
        "          Value must be one of\n"
        "          [3,candidate_selection_based_on_voting,2,self_balancing_binary_tree,1,hierarchical_clustering,0,simple_clustering].\n"
        "    -r, --refinement_method (refinement_methods)\n"
        "          Choose the refinement method to be used. Default: no_refinement.\n"
        "          Value must be one of\n"
        "          [2,sViper_refinement_method,1,sVirl_refinement_method,0,no_refinement].\n"
```

2021-02-19 09:23 UTC, joergi-w requested changes

2021-02-19 09:23 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "          Output file for insertion alleles Write permissions must be granted.\n"
Something is wrong in this line...

2021-02-19 09:23 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "          Whether to to check for the newest app version. Default: 1.\n"
double `to`

2021-02-19 09:23 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "          Whether to to check for the newest app version. Default: 1.\n"
Instead of `1` a `true` would be more user-friendly.

2021-02-19 09:23 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "          Output file for insertion alleles Write permissions must be granted.\n"
Same as above. Please store the common text only _once_ in a (global) variable and then concatenate the parts that change. So you do not need to edit more than 1 place when something changes.

2021-02-19 09:23 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "          Whether to to check for the newest app version. Default: 1.\n"
same as above

2021-02-19 09:23 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "          Choose the method to be used. Default: [1,2,3,4]. Value must be in\n"
- I don't understand this default: All methods at the same time?
- What do the numbers represent? Some kind of legend or explanation is missing.
- "Value must be in..." and "choose the method" assumes there is only one value, but you seem to allow more.

2021-02-19 09:26 UTC, joergi-w requested changes

2021-02-19 09:26 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +        "    -m, --method (List of unsigned 8 bit integer's)\n"
The plural in English doesn't have an apostrophe.
```suggestion
        "    -m, --method (List of unsigned 8 bit integers)\n"
```

2021-03-01 12:57 UTC, Irallia commented
@joergi-w sorry for the amount of new changes. Feel free to just check your requested ones.

2021-03-02 08:50 UTC, joergi-w approved these changes
Looks good, and thanks for the fixes to Argument Parser as well! 
A tiny improvement (not very important):

2021-03-02 08:50 UTC, joergi-w commented on test/cli/detect_breakends_cli_test.cpp
> +std::string help_page_part_1
These strings could be `const`...

2021-03-02 10:18 UTC, joergi-w commented on include/detect_breakends/validator.hpp
> +#include <seqan3/argument_parser/auxiliary.hpp>     // for enumeration_names
Maybe sort these (with the 2nd review)?

2021-03-04 09:09 UTC, joshuak94 approved these changes
Looks good to me!

2021-03-05 15:02 UTC, merged