Set ref_id to -1 and ref_pos to 0 if they are unset. Skip those reads.
seqan/iGenVar pull request #75
Opened 2021-02-26 13:28 UTC by joshuak94

In the case that a read is unmapped, the ref_id/ref_pos could be empty. Previously, ref_id was set to 0, but 0 refers to the first chromosome, which isn't right.

Instead, we should skip those reads which have invalid positions (1-based coordinates) or IDs (0-based). 

I think this should update that!

2021-03-02 12:18 UTC, eldariont requested changes
Looks good. Just two little suggestions based on what we discovered yesterday (the fact that reference positions are 0-based in seqan). I will create a separate issue for that later but as you are already modifying this code, you could just fix it now :)

2021-03-02 12:18 UTC, eldariont commented on src/detect_breakends/junction_detection.cpp
>          const int32_t pos                       = seqan3::get<seqan3::field::ref_offset>(rec).value_or(0);  // 4: POS
According to the [seqan docs](https://docs.seqan.de/seqan/3-master-dev/group__io.html#ga2511b22375848e1bedbc5013c952a817) both ref_id and pos are 0-based. Therefore, you can also set a missing pos to -1:

```suggestion
        const int32_t pos                       = seqan3::get<seqan3::field::ref_offset>(rec).value_or(-1);  // 4: POS
```

2021-03-02 12:18 UTC, eldariont commented on src/detect_breakends/junction_detection.cpp
> +            ref_id < 0 || pos < 1)
Same here:
```suggestion
        if (hasFlagUnmapped(flag) || hasFlagSecondary(flag) || hasFlagDuplicate(flag) || mapq < 20 ||
            ref_id < 0 || pos < 0)
```

2021-03-09 11:05 UTC, eldariont approved these changes
Thanks!

2021-03-09 13:11 UTC, joshuak94 commented
@Irallia Can you merge this one?

2021-03-09 14:55 UTC, merged