[FIX] Fix EnumValidator
seqan/iGenVar pull request #91
Opened 2021-03-19 16:01 UTC by Irallia

Resolves #78 

Update EnumValidator such that `args.methods` (detection_methods) can be used and give a nice help page view.

2021-03-20 10:22 UTC, eseiler approved these changes

2021-03-22 13:17 UTC, Irallia commented on test/cli/iGenVar_cli_test.cpp
> +    };
This unhelpful error message is fixed by issue https://github.com/seqan/seqan3/issues/2464.

2021-04-07 12:46 UTC, eldariont requested changes
Looks very good. I only have one tiny comment about the test cases.

2021-04-07 12:46 UTC, eldariont commented on test/cli/iGenVar_cli_test.cpp
> +    std::string expected_res
This local variable has the same name as the global variable above. Maybe rename to `expected_res_no_options`?

2021-04-07 12:46 UTC, eldariont commented on test/cli/iGenVar_cli_test.cpp
> +    std::string expected_res
Or we move the global variable into the test cases which use it? I guess we could decide to either define all result and error messages above the test cases or inside each test case. A mix of both is confusing.

2021-04-07 14:27 UTC, eldariont approved these changes
Thanks!

2021-04-08 10:06 UTC, merged